---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-NicoVideo
no_index:
  directory:
    - t
    - inc
requires:
  CGI::Simple: 0
  Class::Accessor::Fast: 0
  HTML::Parser: 3
  HTTP::Cookies: 0
  HTTP::Request::Common: 0
  JSON: 2.01
  LWP::UserAgent: 0
  Test::More: 0.32
  XML::FeedPP: 0
  XML::TreePP: 0
version: 0.01_20
